<optgroup label="Africa" >
<option value="Africa/Abidjan" <?php selected( $value,'Africa/Abidjan');?> ><?php _e('Africa/Abidjan','profile-magic');?></option>
<option value="Africa/Accra" <?php selected( $value,'Africa/Accra');?> ><?php _e('Accra','profile-magic');?></option>
<option value="Africa/Addis_Ababa" <?php selected( $value,'Africa/Addis_Ababa');?> ><?php _e('Addis_Ababa','profile-magic');?></option>
<option value="Africa/Algiers" <?php selected( $value,'Africa/Algiers');?> ><?php _e('Algiers','profile-magic');?></option>
<option value="Africa/Asmara" <?php selected( $value,'Africa/Asmara');?> ><?php _e('Asmara','profile-magic');?></option>
<option value="Africa/Bamako" <?php selected( $value,'Africa/Bamako');?> ><?php _e('Bamako','profile-magic');?></option>
<option value="Africa/Bangui" <?php selected( $value,'Africa/Bangui');?> ><?php _e('Bangui','profile-magic');?></option>
<option value="Africa/Banjul" <?php selected( $value,'Africa/Banjul');?> ><?php _e('Banjul','profile-magic');?></option>
<option value="Africa/Bissau" <?php selected( $value,'Africa/Bissau');?> ><?php _e('Bissau','profile-magic');?></option>
<option value="Africa/Blantyre" <?php selected( $value,'Africa/Blantyre');?> ><?php _e('Blantyre','profile-magic');?></option>
<option value="Africa/Brazzaville" <?php selected( $value,'Africa/Brazzaville');?> ><?php _e('Brazzaville','profile-magic');?></option>
<option value="Africa/Bujumbura" <?php selected( $value,'Africa/Bujumbura');?> ><?php _e('Bujumbura','profile-magic');?></option>
<option value="Africa/Cairo" <?php selected( $value,'Africa/Cairo');?> ><?php _e('Cairo','profile-magic');?></option>
<option value="Africa/Casablanca" <?php selected( $value,'Africa/Casablanca');?> ><?php _e('Casablanca','profile-magic');?></option>
<option value="Africa/Ceuta" <?php selected( $value,'Africa/Ceuta');?> ><?php _e('Ceuta','profile-magic');?></option>
<option value="Africa/Conakry" <?php selected( $value,'Africa/Conakry');?> ><?php _e('Conakry','profile-magic');?></option>
<option value="Africa/Dakar" <?php selected( $value,'Africa/Dakar');?> ><?php _e('Dakar','profile-magic');?></option>
<option value="Africa/Dar_es_Salaam" <?php selected( $value,'Africa/Dar_es_Salaam');?> ><?php _e('Dar_es_Salaam','profile-magic');?></option>
<option value="Africa/Djibouti" <?php selected( $value,'Africa/Djibouti');?> ><?php _e('Djibouti','profile-magic');?></option>
<option value="Africa/Douala" <?php selected( $value,'Africa/Douala');?> ><?php _e('Douala','profile-magic');?></option>
<option value="Africa/El_Aaiun" <?php selected( $value,'Africa/El_Aaiun');?> ><?php _e('El_Aaiun','profile-magic');?></option>
<option value="Africa/Freetown" <?php selected( $value,'Africa/Freetown');?> ><?php _e('Freetown','profile-magic');?></option>
<option value="Africa/Gaborone" <?php selected( $value,'Africa/Gaborone');?> ><?php _e('Gaborone','profile-magic');?></option>
<option value="Africa/Harare" <?php selected( $value,'Africa/Harare');?> ><?php _e('Harare','profile-magic');?></option>
<option value="Africa/Johannesburg" <?php selected( $value,'Africa/Johannesburg');?> ><?php _e('Johannesburg','profile-magic');?></option>
<option value="Africa/Juba" <?php selected( $value,'Africa/Juba');?> ><?php _e('Juba','profile-magic');?></option>
<option value="Africa/Kampala" <?php selected( $value,'Africa/Kampala');?> ><?php _e('Kampala','profile-magic');?></option>
<option value="Africa/Khartoum" <?php selected( $value,'Africa/Khartoum');?> ><?php _e('Khartoum','profile-magic');?></option>
<option value="Africa/Kigali" <?php selected( $value,'Africa/Kigali');?> ><?php _e('Kigali','profile-magic');?></option>
<option value="Africa/Kinshasa" <?php selected( $value,'Africa/Kinshasa');?> ><?php _e('Kinshasa','profile-magic');?></option>
<option value="Africa/Lagos" <?php selected( $value,'Africa/Lagos');?> ><?php _e('Lagos','profile-magic');?></option>
<option value="Africa/Libreville" <?php selected( $value,'Africa/Libreville');?> ><?php _e('Libreville','profile-magic');?></option>
<option value="Africa/Lome" <?php selected( $value,'Africa/Lome');?> ><?php _e('Lome','profile-magic');?></option>
<option value="Africa/Luanda" <?php selected( $value,'Africa/Luanda');?> ><?php _e('Luanda','profile-magic');?></option>
<option value="Africa/Lubumbashi" <?php selected( $value,'Africa/Lubumbashi');?> ><?php _e('Lubumbashi','profile-magic');?></option>
<option value="Africa/Lusaka" <?php selected( $value,'Africa/Lusaka');?> ><?php _e('Lusaka','profile-magic');?></option>
<option value="Africa/Malabo" <?php selected( $value,'Africa/Malabo');?> ><?php _e('Malabo','profile-magic');?></option>
<option value="Africa/Maputo" <?php selected( $value,'Africa/Maputo');?> ><?php _e('Maputo','profile-magic');?></option>
<option value="Africa/Maseru" <?php selected( $value,'Africa/Maseru');?> ><?php _e('Maseru','profile-magic');?></option>
<option value="Africa/Mbabane" <?php selected( $value,'Africa/Mbabane');?> ><?php _e('Mbabane','profile-magic');?></option>
<option value="Africa/Mogadishu" <?php selected( $value,'Africa/Mogadishu');?> ><?php _e('Mogadishu','profile-magic');?></option>
<option value="Africa/Monrovia" <?php selected( $value,'Africa/Monrovia');?> ><?php _e('Monrovia','profile-magic');?></option>
<option value="Africa/Nairobi" <?php selected( $value,'Africa/Nairobi');?> ><?php _e('Nairobi','profile-magic');?></option>
<option value="Africa/Ndjamena" <?php selected( $value,'Africa/Ndjamena');?> ><?php _e('Ndjamena','profile-magic');?></option>
<option value="Africa/Niamey" <?php selected( $value,'Africa/Niamey');?> ><?php _e('Niamey','profile-magic');?></option>
<option value="Africa/Nouakchott" <?php selected( $value,'Africa/Nouakchott');?> ><?php _e('Nouakchott','profile-magic');?></option>
<option value="Africa/Ouagadougou" <?php selected( $value,'Africa/Ouagadougou');?> ><?php _e('Ouagadougou','profile-magic');?></option>
<option value="Africa/Porto-Novo" <?php selected( $value,'Africa/Porto-Novo');?> ><?php _e('Porto-Novo','profile-magic');?></option>
<option value="Africa/Sao_Tome" <?php selected( $value,'Africa/Sao_Tome');?> ><?php _e('Sao_Tome','profile-magic');?></option>
<option value="Africa/Tripoli" <?php selected( $value,'Africa/Tripoli');?> ><?php _e('Tripoli','profile-magic');?></option>
<option value="Africa/Tunis" <?php selected( $value,'Africa/Tunis');?> ><?php _e('Tunis','profile-magic');?></option>
<option value="Africa/Windhoek" <?php selected( $value,'Africa/Windhoek');?> ><?php _e('Windhoek','profile-magic');?></option>
</optgroup>
<optgroup label="America">
<option value="America/Adak" <?php selected( $value,'America/Adak');?> ><?php _e('Adak','profile-magic');?></option>
<option value="America/Anchorage" <?php selected( $value,'America/Anchorage');?> ><?php _e('Anchorage','profile-magic');?></option>
<option value="America/Anguilla" <?php selected( $value,'America/Anguilla');?> ><?php _e('Anguilla','profile-magic');?></option>
<option value="America/Antigua" <?php selected( $value,'America/Antigua');?> ><?php _e('Antigua','profile-magic');?></option>
<option value="America/Araguaina" <?php selected( $value,'America/Araguaina');?> ><?php _e('Araguaina','profile-magic');?></option>
<option value="America/Argentina/Buenos_Aires" <?php selected( $value,'America/Argentina - Buenos Aires');?> ><?php _e('Argentina - Buenos Aires','profile-magic');?></option>
<option value="America/Argentina/Catamarca" <?php selected( $value,'America/Argentina - Catamarca');?> ><?php _e('Argentina - Catamarca','profile-magic');?></option>
<option value="America/Argentina/Cordoba" <?php selected( $value,'America/Argentina - Cordoba');?> ><?php _e('Argentina - Cordoba','profile-magic');?></option>
<option value="America/Argentina/Jujuy" <?php selected( $value,'America/Argentina - Jujuy');?> ><?php _e('Argentina - Jujuy','profile-magic');?></option>
<option value="America/Argentina/La_Rioja" <?php selected( $value,'America/Argentina - La Rioja');?> ><?php _e('Argentina - La Rioja','profile-magic');?></option>
<option value="America/Argentina/Mendoza" <?php selected( $value,'America/Argentina - Mendoza');?> ><?php _e('Argentina - Mendoza','profile-magic');?></option>
<option value="America/Argentina/Rio_Gallegos" <?php selected( $value,'America/Argentina - Rio Gallegos');?> ><?php _e('Argentina - Rio Gallegos','profile-magic');?></option>
<option value="America/Argentina/Salta" <?php selected( $value,'America/Argentina - Salta');?> ><?php _e('Argentina - Salta','profile-magic');?></option>
<option value="America/Argentina/San_Juan" <?php selected( $value,'America/Argentina - San Juan');?> ><?php _e('Argentina - San Juan','profile-magic');?></option>
<option value="America/Argentina/San_Luis" <?php selected( $value,'America/Argentina - San Luis');?> ><?php _e('Argentina - San Luis','profile-magic');?></option>
<option value="America/Argentina/Tucuman" <?php selected( $value,'America/Argentina - Tucuman');?> ><?php _e('Argentina - Tucuman','profile-magic');?></option>
<option value="America/Argentina/Ushuaia" <?php selected( $value,'America/Argentina - Ushuaia');?> ><?php _e('Argentina - Ushuaia','profile-magic');?></option>
<option value="America/Aruba" <?php selected( $value,'America/Aruba');?> ><?php _e('Aruba','profile-magic');?></option>
<option value="America/Asuncion" <?php selected( $value,'America/Asuncion');?> ><?php _e('Asuncion','profile-magic');?></option>
<option value="America/Atikokan" <?php selected( $value,'America/Atikokan');?> ><?php _e('Atikokan','profile-magic');?></option>
<option value="America/Bahia" <?php selected( $value,'America/Bahia');?> ><?php _e('Bahia','profile-magic');?></option>
<option value="America/Bahia_Banderas" <?php selected( $value,'America/Bahia Banderas');?> ><?php _e('Bahia Banderas','profile-magic');?></option>
<option value="America/Barbados" <?php selected( $value,'America/Barbados');?> ><?php _e('Barbados','profile-magic');?></option>
<option value="America/Belem" <?php selected( $value,'America/Belem');?> ><?php _e('Belem','profile-magic');?></option>
<option value="America/Belize" <?php selected( $value,'America/Belize');?> ><?php _e('Belize','profile-magic');?></option>
<option value="America/Blanc-Sablon" <?php selected( $value,'America/Blanc-Sablon');?> ><?php _e('Blanc-Sablon','profile-magic');?></option>
<option value="America/Boa_Vista" <?php selected( $value,'America/Boa Vista');?> ><?php _e('Boa Vista','profile-magic');?></option>
<option value="America/Bogota" <?php selected( $value,'America/Bogota');?> ><?php _e('Bogota','profile-magic');?></option>
<option value="America/Boise" <?php selected( $value,'America/Boise');?> ><?php _e('Boise','profile-magic');?></option>
<option value="America/Cambridge_Bay" <?php selected( $value,'America/Cambridge Bay');?> ><?php _e('Cambridge Bay','profile-magic');?></option>
<option value="America/Campo_Grande" <?php selected( $value,'America/Campo Grande');?> ><?php _e('Campo Grande','profile-magic');?></option>
<option value="America/Cancun" <?php selected( $value,'America/Cancun');?> ><?php _e('Cancun','profile-magic');?></option>
<option value="America/Caracas" <?php selected( $value,'America/Caracas');?> ><?php _e('Caracas','profile-magic');?></option>
<option value="America/Cayenne" <?php selected( $value,'America/Cayenne');?> ><?php _e('Cayenne','profile-magic');?></option>
<option value="America/Cayman" <?php selected( $value,'America/Cayman');?> ><?php _e('Cayman','profile-magic');?></option>
<option value="America/Chicago" <?php selected( $value,'America/Chicago');?> ><?php _e('Chicago','profile-magic');?></option>
<option value="America/Chihuahua" <?php selected( $value,'America/Chihuahua');?> ><?php _e('Chihuahua','profile-magic');?></option>
<option value="America/Costa_Rica" <?php selected( $value,'America/Costa Rica');?> ><?php _e('Costa Rica','profile-magic');?></option>
<option value="America/Creston" <?php selected( $value,'America/Creston');?> ><?php _e('Creston','profile-magic');?></option>
<option value="America/Cuiaba" <?php selected( $value,'America/Cuiaba');?> ><?php _e('Cuiaba','profile-magic');?></option>
<option value="America/Curacao" <?php selected( $value,'America/Curacao');?> ><?php _e('Curacao','profile-magic');?></option>
<option value="America/Danmarkshavn" <?php selected( $value,'America/Danmarkshavn');?> ><?php _e('Danmarkshavn','profile-magic');?></option>
<option value="America/Dawson" <?php selected( $value,'America/Dawson');?> ><?php _e('Dawson','profile-magic');?></option>
<option value="America/Dawson_Creek" <?php selected( $value,'America/Dawson Creek');?> ><?php _e('Dawson Creek','profile-magic');?></option>
<option value="America/Denver" <?php selected( $value,'America/Denver');?> ><?php _e('Denver','profile-magic');?></option>
<option value="America/Detroit" <?php selected( $value,'America/Detroit');?> ><?php _e('Detroit','profile-magic');?></option>
<option value="America/Dominica" <?php selected( $value,'America/Dominica');?> ><?php _e('Dominica','profile-magic');?></option>
<option value="America/Edmonton" <?php selected( $value,'America/Edmonton');?> ><?php _e('Edmonton','profile-magic');?></option>
<option value="America/Eirunepe" <?php selected( $value,'America/Eirunepe');?> ><?php _e('Eirunepe','profile-magic');?></option>
<option value="America/El_Salvador" <?php selected( $value,'America/El Salvador');?> ><?php _e('El Salvador','profile-magic');?></option>
<option value="America/Fortaleza" <?php selected( $value,'America/Fortaleza');?> ><?php _e('Fortaleza','profile-magic');?></option>
<option value="America/Glace_Bay" <?php selected( $value,'America/Glace Bay');?> ><?php _e('Glace Bay','profile-magic');?></option>
<option value="America/Godthab" <?php selected( $value,'America/Godthab');?> ><?php _e('Godthab','profile-magic');?></option>
<option value="America/Goose_Bay" <?php selected( $value,'America/Goose Bay');?> ><?php _e('Goose Bay','profile-magic');?></option>
<option value="America/Grand_Turk" <?php selected( $value,'America/Grand Turk');?> ><?php _e('Grand Turk','profile-magic');?></option>
<option value="America/Grenada" <?php selected( $value,'America/Grenada');?> ><?php _e('Grenada','profile-magic');?></option>
<option value="America/Guadeloupe" <?php selected( $value,'America/Guadeloupe');?> ><?php _e('Guadeloupe','profile-magic');?></option>
<option value="America/Guatemala" <?php selected( $value,'America/Guatemala');?> ><?php _e('Guatemala','profile-magic');?></option>
<option value="America/Guayaquil" <?php selected( $value,'America/Guayaquil');?> ><?php _e('Guayaquil','profile-magic');?></option>
<option value="America/Guyana" <?php selected( $value,'America/Guyana');?> ><?php _e('Guyana','profile-magic');?></option>
<option value="America/Halifax" <?php selected( $value,'America/Halifax');?> ><?php _e('Halifax','profile-magic');?></option>
<option value="America/Havana" <?php selected( $value,'America/Havana');?> ><?php _e('Havana','profile-magic');?></option>
<option value="America/Hermosillo" <?php selected( $value,'America/Hermosillo');?> ><?php _e('Hermosillo','profile-magic');?></option>
<option value="America/Indiana/Indianapolis" <?php selected( $value,'America/Indiana - Indianapolis');?> ><?php _e('Indiana - Indianapolis','profile-magic');?></option>
<option value="America/Indiana/Knox" <?php selected( $value,'America/Indiana - Knox');?> ><?php _e('Indiana - Knox','profile-magic');?></option>
<option value="America/Indiana/Marengo" <?php selected( $value,'America/Indiana - Marengo');?> ><?php _e('Indiana - Marengo','profile-magic');?></option>
<option value="America/Indiana/Petersburg" <?php selected( $value,'America/Indiana - Petersburg');?> ><?php _e('Indiana - Petersburg','profile-magic');?></option>
<option value="America/Indiana/Tell_City" <?php selected( $value,'America/Indiana - Tell City');?> ><?php _e('Indiana - Tell City','profile-magic');?></option>
<option value="America/Indiana/Vevay" <?php selected( $value,'America/Indiana - Vevay');?> ><?php _e('Indiana - Vevay','profile-magic');?></option>
<option value="America/Indiana/Vincennes" <?php selected( $value,'America/Indiana - Vincennes');?> ><?php _e('Indiana - Vincennes','profile-magic');?></option>
<option value="America/Indiana/Winamac" <?php selected( $value,'America/Indiana - Winamac');?> ><?php _e('Indiana - Winamac','profile-magic');?></option>
<option value="America/Inuvik" <?php selected( $value,'America/Inuvik');?> ><?php _e('Inuvik','profile-magic');?></option>
<option value="America/Iqaluit" <?php selected( $value,'America/Iqaluit');?> ><?php _e('Iqaluit','profile-magic');?></option>
<option value="America/Jamaica" <?php selected( $value,'America/Jamaica');?> ><?php _e('Jamaica','profile-magic');?></option>
<option value="America/Juneau" <?php selected( $value,'America/Juneau');?> ><?php _e('Juneau','profile-magic');?></option>
<option value="America/Kentucky/Louisville" <?php selected( $value,'America/Kentucky - Louisville');?> ><?php _e('Kentucky - Louisville','profile-magic');?></option>
<option value="America/Kentucky/Monticello" <?php selected( $value,'America/Kentucky - Monticello');?> ><?php _e('Kentucky - Monticello','profile-magic');?></option>
<option value="America/Kralendijk" <?php selected( $value,'America/Kralendijk');?> ><?php _e('Kralendijk','profile-magic');?></option>
<option value="America/La_Paz" <?php selected( $value,'America/La Paz');?> ><?php _e('La Paz','profile-magic');?></option>
<option value="America/Lima" <?php selected( $value,'America/Lima');?> ><?php _e('Lima','profile-magic');?></option>
<option value="America/Los_Angeles" <?php selected( $value,'America/Los Angeles');?> ><?php _e('Los Angeles','profile-magic');?></option>
<option value="America/Lower_Princes" <?php selected( $value,'America/Lower Princes');?> ><?php _e('Lower Princes','profile-magic');?></option>
<option value="America/Maceio" <?php selected( $value,'America/Maceio');?> ><?php _e('Maceio','profile-magic');?></option>
<option value="America/Managua" <?php selected( $value,'America/Managua');?> ><?php _e('Managua','profile-magic');?></option>
<option value="America/Manaus" <?php selected( $value,'America/Manaus');?> ><?php _e('Manaus','profile-magic');?></option>
<option value="America/Marigot" <?php selected( $value,'America/Marigot');?> ><?php _e('Marigot','profile-magic');?></option>
<option value="America/Martinique" <?php selected( $value,'America/Martinique');?> ><?php _e('Martinique','profile-magic');?></option>
<option value="America/Matamoros" <?php selected( $value,'America/Matamoros');?> ><?php _e('Matamoros','profile-magic');?></option>
<option value="America/Mazatlan" <?php selected( $value,'America/Mazatlan');?> ><?php _e('Mazatlan','profile-magic');?></option>
<option value="America/Menominee" <?php selected( $value,'America/Menominee');?> ><?php _e('Menominee','profile-magic');?></option>
<option value="America/Merida" <?php selected( $value,'America/Merida');?> ><?php _e('Merida','profile-magic');?></option>
<option value="America/Metlakatla" <?php selected( $value,'America/Metlakatla');?> ><?php _e('Metlakatla','profile-magic');?></option>
<option value="America/Mexico_City" <?php selected( $value,'America/Mexico City');?> ><?php _e('Mexico City','profile-magic');?></option>
<option value="America/Miquelon" <?php selected( $value,'America/Miquelon');?> ><?php _e('Miquelon','profile-magic');?></option>
<option value="America/Moncton" <?php selected( $value,'America/Moncton');?> ><?php _e('Moncton','profile-magic');?></option>
<option value="America/Monterrey" <?php selected( $value,'America/Monterrey');?> ><?php _e('Monterrey','profile-magic');?></option>
<option value="America/Montevideo" <?php selected( $value,'America/Montevideo');?> ><?php _e('Montevideo','profile-magic');?></option>
<option value="America/Montserrat" <?php selected( $value,'America/Montserrat');?> ><?php _e('Montserrat','profile-magic');?></option>
<option value="America/Nassau" <?php selected( $value,'America/Nassau');?> ><?php _e('Nassau','profile-magic');?></option>
<option value="America/New_York" <?php selected( $value,'America/New York');?> ><?php _e('New York','profile-magic');?></option>
<option value="America/Nipigon" <?php selected( $value,'America/Nipigon');?> ><?php _e('Nipigon','profile-magic');?></option>
<option value="America/Nome" <?php selected( $value,'America/Nome');?> ><?php _e('Nome','profile-magic');?></option>
<option value="America/Noronha" <?php selected( $value,'America/Noronha');?> ><?php _e('Noronha','profile-magic');?></option>
<option value="America/North_Dakota/Beulah" <?php selected( $value,'America/Noronha');?> ><?php _e('North Dakota - Beulah','profile-magic');?></option>
<option value="America/North_Dakota/Center" <?php selected( $value,'America/North Dakota - Center');?> ><?php _e('North Dakota - Center','profile-magic');?></option>
<option value="America/North_Dakota/New_Salem" <?php selected( $value,'America/North Dakota - New Salem');?> ><?php _e('North Dakota - New Salem','profile-magic');?></option>
<option value="America/Ojinaga" <?php selected( $value,'America/Ojinaga');?> ><?php _e('Ojinaga','profile-magic');?></option>
<option value="America/Panama" <?php selected( $value,'Panama');?> ><?php _e('Panama','profile-magic');?></option>
<option value="America/Pangnirtung" <?php selected( $value,'America/Pangnirtung');?> ><?php _e('Pangnirtung','profile-magic');?></option>
<option value="America/Paramaribo" <?php selected( $value,'America/Paramaribo');?> ><?php _e('Paramaribo','profile-magic');?></option>
<option value="America/Phoenix" <?php selected( $value,'America/Phoenix');?> ><?php _e('Phoenix','profile-magic');?></option>
<option value="America/Port-au-Prince" <?php selected( $value,'America/Port-au-Prince');?> ><?php _e('Port-au-Prince','profile-magic');?></option>
<option value="America/Port_of_Spain" <?php selected( $value,'America/Port of Spain');?> ><?php _e('Port of Spain','profile-magic');?></option>
<option value="America/Porto_Velho" <?php selected( $value,'America/Porto Velho');?> ><?php _e('Porto Velho','profile-magic');?></option>
<option value="America/Puerto_Rico" <?php selected( $value,'America/Puerto Rico');?> ><?php _e('Puerto Rico','profile-magic');?></option>
<option value="America/Rainy_River" <?php selected( $value,'America/Rainy River');?> ><?php _e('Rainy River','profile-magic');?></option>
<option value="America/Rankin_Inlet" <?php selected( $value,'America/Rankin Inlet');?> ><?php _e('Rankin Inlet','profile-magic');?></option>
<option value="America/Recife" <?php selected( $value,'America/Recife');?> ><?php _e('Recife','profile-magic');?></option>
<option value="America/Regina" <?php selected( $value,'America/Regina');?> ><?php _e('Regina','profile-magic');?></option>
<option value="America/Resolute" <?php selected( $value,'America/Resolute');?> ><?php _e('Resolute','profile-magic');?></option>
<option value="America/Rio_Branco" <?php selected( $value,'America/Rio Branco');?> ><?php _e('Rio Branco','profile-magic');?></option>
<option value="America/Santa_Isabel" <?php selected( $value,'America/Santa Isabel');?> ><?php _e('Santa Isabel','profile-magic');?></option>
<option value="America/Santarem" <?php selected( $value,'America/Santarem');?> ><?php _e('Santarem','profile-magic');?></option>
<option value="America/Santiago" <?php selected( $value,'America/Santiago');?> ><?php _e('Santiago','profile-magic');?></option>
<option value="America/Santo_Domingo" <?php selected( $value,'America/Santo Domingo');?> ><?php _e('Santo Domingo','profile-magic');?></option>
<option value="America/Sao_Paulo" <?php selected( $value,'America/Sao Paulo');?> ><?php _e('Sao Paulo','profile-magic');?></option>
<option value="America/Scoresbysund" <?php selected( $value,'America/Scoresbysund');?> ><?php _e('Scoresbysund','profile-magic');?></option>
<option value="America/Sitka" <?php selected( $value,'America/Sitka');?> ><?php _e('Sitka','profile-magic');?></option>
<option value="America/St_Barthelemy" <?php selected( $value,'America/St Barthelemy');?> ><?php _e('St Barthelemy','profile-magic');?></option>
<option value="America/St_Johns" <?php selected( $value,'America/St Johns');?> ><?php _e('St Johns','profile-magic');?></option>
<option value="America/St_Kitts" <?php selected( $value,'America/St Kitts');?> ><?php _e('St Kitts','profile-magic');?></option>
<option value="America/St_Lucia" <?php selected( $value,'America/St Lucia');?> ><?php _e('St Lucia','profile-magic');?></option>
<option value="America/St_Thomas" <?php selected( $value,'America/St Thomas');?> ><?php _e('St Thomas','profile-magic');?></option>
<option value="America/St_Vincent" <?php selected( $value,'America/St Vincent');?> ><?php _e('St Vincent','profile-magic');?></option>
<option value="America/Swift_Current" <?php selected( $value,'America/Swift Current');?> ><?php _e('Swift Current','profile-magic');?></option>
<option value="America/Tegucigalpa" <?php selected( $value,'America/Tegucigalpa');?> ><?php _e('Tegucigalpa','profile-magic');?></option>
<option value="America/Thule" <?php selected( $value,'America/Thule');?> ><?php _e('Thule','profile-magic');?></option>
<option value="America/Thunder_Bay" <?php selected( $value,'America/Thunder Bay');?> ><?php _e('Thunder Bay','profile-magic');?></option>
<option value="America/Tijuana" <?php selected( $value,'America/Tijuana');?> ><?php _e('Tijuana','profile-magic');?></option>
<option value="America/Toronto" <?php selected( $value,'America/Toronto');?> ><?php _e('Toronto','profile-magic');?></option>
<option value="America/Tortola" <?php selected( $value,'America/Tortola');?> ><?php _e('Tortola','profile-magic');?></option>
<option value="America/Vancouver" <?php selected( $value,'America/Vancouver');?> ><?php _e('Vancouver','profile-magic');?></option>
<option value="America/Whitehorse" <?php selected( $value,'America/Whitehorse');?> ><?php _e('Whitehorse','profile-magic');?></option>
<option value="America/Winnipeg" <?php selected( $value,'America/Winnipeg');?> ><?php _e('Winnipeg','profile-magic');?></option>
<option value="America/Yakutat" <?php selected( $value,'America/Yakutat');?> ><?php _e('Yakutat','profile-magic');?></option>
<option value="America/Yellowknife" <?php selected( $value,'America/Yellowknife');?> ><?php _e('Yellowknife','profile-magic');?></option>
</optgroup>
<optgroup label="Antarctica">
<option value="Antarctica/Casey" <?php selected( $value,'Antarctica/Casey');?> ><?php _e('Casey','profile-magic');?></option>
<option value="Antarctica/Davis" <?php selected( $value,'Antarctica/Davis');?> ><?php _e('Davis','profile-magic');?></option>
<option value="Antarctica/DumontDUrville" <?php selected( $value,'Antarctica/DumontDUrville');?> ><?php _e('DumontDUrville','profile-magic');?></option>
<option value="Antarctica/Macquarie" <?php selected( $value,'Antarctica/Macquarie');?> ><?php _e('Macquarie','profile-magic');?></option>
<option value="Antarctica/Mawson" <?php selected( $value,'Antarctica/Mawson');?> ><?php _e('Mawson','profile-magic');?></option>
<option value="Antarctica/McMurdo" <?php selected( $value,'Antarctica/McMurdo');?> ><?php _e('McMurdo','profile-magic');?></option>
<option value="Antarctica/Palmer" <?php selected( $value,'Antarctica/Palmer');?> ><?php _e('Palmer','profile-magic');?></option>
<option value="Antarctica/Rothera" <?php selected( $value,'Antarctica/Rothera');?> ><?php _e('Rothera','profile-magic');?></option>
<option value="Antarctica/Syowa" <?php selected( $value,'Antarctica/Syowa');?> ><?php _e('Syowa','profile-magic');?></option>
<option value="Antarctica/Troll" <?php selected( $value,'Antarctica/Troll');?> ><?php _e('Troll','profile-magic');?></option>
<option value="Antarctica/Vostok" <?php selected( $value,'Antarctica/Vostok');?> ><?php _e('Vostok','profile-magic');?></option>
</optgroup>
<optgroup label="Arctic" >
<option value="Arctic/Longyearbyen" <?php selected( $value,'Arctic/Longyearbyen');?> ><?php _e('Longyearbyen','profile-magic');?></option>
</optgroup>
<optgroup label="Asia">
<option value="Asia/Aden" <?php selected( $value,'Asia/Aden');?> ><?php _e('Aden','profile-magic');?></option>
<option value="Asia/Almaty" <?php selected( $value,'Asia/Almaty');?> ><?php _e('Almaty','profile-magic');?></option>
<option value="Asia/Amman" <?php selected( $value,'Asia/Amman');?> ><?php _e('Amman','profile-magic');?></option>
<option value="Asia/Anadyr" <?php selected( $value,'Asia/Anadyr');?> ><?php _e('Anadyr','profile-magic');?></option>
<option value="Asia/Aqtau" <?php selected( $value,'Asia/Aqtau');?> ><?php _e('Aqtau','profile-magic');?></option>
<option value="Asia/Aqtobe" <?php selected( $value,'Asia/Aqtobe');?> ><?php _e('Aqtobe','profile-magic');?></option>
<option value="Asia/Ashgabat" <?php selected( $value,'Asia/Ashgabat');?> ><?php _e('Ashgabat','profile-magic');?></option>
<option value="Asia/Baghdad" <?php selected( $value,'Asia/Baghdad');?> ><?php _e('Baghdad','profile-magic');?></option>
<option value="Asia/Bahrain" <?php selected( $value,'Asia/Bahrain');?> ><?php _e('Bahrain','profile-magic');?></option>
<option value="Asia/Baku" <?php selected( $value,'Asia/Baku');?> ><?php _e('Baku','profile-magic');?></option>
<option value="Asia/Bangkok" <?php selected( $value,'Asia/Bangkok');?> ><?php _e('Bangkok','profile-magic');?></option>
<option value="Asia/Beirut" <?php selected( $value,'Asia/Beirut');?> ><?php _e('Beirut','profile-magic');?></option>
<option value="Asia/Bishkek" <?php selected( $value,'Asia/Bishkek');?> ><?php _e('Bishkek','profile-magic');?></option>
<option value="Asia/Brunei" <?php selected( $value,'Asia/Brunei');?> ><?php _e('Brunei','profile-magic');?></option>
<option value="Asia/Choibalsan" <?php selected( $value,'Asia/Choibalsan');?> ><?php _e('Choibalsan','profile-magic');?></option>
<option value="Asia/Chongqing" <?php selected( $value,'Asia/Chongqing');?> ><?php _e('Chongqing','profile-magic');?></option>
<option value="Asia/Colombo" <?php selected( $value,'Asia/Colombo');?> ><?php _e('Colombo','profile-magic');?></option>
<option value="Asia/Damascus" <?php selected( $value,'Asia/Damascus');?> ><?php _e('Damascus','profile-magic');?></option>
<option value="Asia/Dhaka" <?php selected( $value,'Asia/Dhaka');?> ><?php _e('Dhaka','profile-magic');?></option>
<option value="Asia/Dili" <?php selected( $value,'Asia/Dili');?> ><?php _e('Dili','profile-magic');?></option>
<option value="Asia/Dubai" <?php selected( $value,'Asia/Dubai');?> ><?php _e('Dubai','profile-magic');?></option>
<option value="Asia/Dushanbe" <?php selected( $value,'Asia/Dushanbe');?> ><?php _e('Dushanbe','profile-magic');?></option>
<option value="Asia/Gaza" <?php selected( $value,'Asia/Gaza');?> ><?php _e('Gaza','profile-magic');?></option>
<option value="Asia/Harbin" <?php selected( $value,'Asia/Harbin');?> ><?php _e('Harbin','profile-magic');?></option>
<option value="Asia/Hebron" <?php selected( $value,'Asia/Hebron');?> ><?php _e('Hebron','profile-magic');?></option>
<option value="Asia/Ho_Chi_Minh" <?php selected( $value,'Asia/Ho Chi Minh');?> ><?php _e('Ho Chi Minh','profile-magic');?></option>
<option value="Asia/Hong_Kong" <?php selected( $value,'Asia/Hong Kong');?> ><?php _e('Hong Kong','profile-magic');?></option>
<option value="Asia/Hovd" <?php selected( $value,'Asia/Hovd');?> ><?php _e('Hovd','profile-magic');?></option>
<option value="Asia/Irkutsk" <?php selected( $value,'Asia/Irkutsk');?> ><?php _e('Irkutsk','profile-magic');?></option>
<option value="Asia/Jakarta" <?php selected( $value,'Asia/Jakarta');?> ><?php _e('Jakarta','profile-magic');?></option>
<option value="Asia/Jayapura" <?php selected( $value,'Asia/Jayapura');?> ><?php _e('Jayapura','profile-magic');?></option>
<option value="Asia/Jerusalem" <?php selected( $value,'Asia/Jerusalem');?> ><?php _e('Jerusalem','profile-magic');?></option>
<option value="Asia/Kabul" <?php selected( $value,'Asia/Kabul');?> ><?php _e('Kabul','profile-magic');?></option>
<option value="Asia/Kamchatka" <?php selected( $value,'Asia/Kamchatka');?> ><?php _e('Kamchatka','profile-magic');?></option>
<option value="Asia/Karachi" <?php selected( $value,'Asia/Karachi');?> ><?php _e('Karachi','profile-magic');?></option>
<option value="Asia/Kashgar" <?php selected( $value,'Asia/Kashgar');?> ><?php _e('Kashgar','profile-magic');?></option>
<option value="Asia/Kathmandu" <?php selected( $value,'Asia/Kathmandu');?> ><?php _e('Kathmandu','profile-magic');?></option>
<option value="Asia/Khandyga" <?php selected( $value,'Asia/Khandyga');?> ><?php _e('Khandyga','profile-magic');?></option>
<option value="Asia/Kolkata" <?php selected( $value,'Asia/Kolkata');?> ><?php _e('Kolkata','profile-magic');?></option>
<option value="Asia/Krasnoyarsk" <?php selected( $value,'Asia/Krasnoyarsk');?> ><?php _e('Krasnoyarsk','profile-magic');?></option>
<option value="Asia/Kuala_Lumpur" <?php selected( $value,'Asia/Kuala Lumpur');?> ><?php _e('Kuala Lumpur','profile-magic');?></option>
<option value="Asia/Kuching" <?php selected( $value,'Asia/Kuching');?> ><?php _e('Kuching','profile-magic');?></option>
<option value="Asia/Kuwait" <?php selected( $value,'Asia/Kuwait');?> ><?php _e('Kuwait','profile-magic');?></option>
<option value="Asia/Macau" <?php selected( $value,'Asia/Macau');?> ><?php _e('Macau','profile-magic');?></option>
<option value="Asia/Magadan" <?php selected( $value,'Asia/Magadan');?> ><?php _e('Magadan','profile-magic');?></option>
<option value="Asia/Makassar" <?php selected( $value,'Asia/Makassar');?> ><?php _e('Makassar','profile-magic');?></option>
<option value="Asia/Manila" <?php selected( $value,'Asia/Manila');?> ><?php _e('Manila','profile-magic');?></option>
<option value="Asia/Muscat" <?php selected( $value,'Asia/Muscat');?> ><?php _e('Muscat','profile-magic');?></option>
<option value="Asia/Nicosia" <?php selected( $value,'Asia/Nicosia');?> ><?php _e('Nicosia','profile-magic');?></option>
<option value="Asia/Novokuznetsk" <?php selected( $value,'Asia/Novokuznetsk');?> ><?php _e('Novokuznetsk','profile-magic');?></option>
<option value="Asia/Novosibirsk" <?php selected( $value,'Asia/Novosibirsk');?> ><?php _e('Novosibirsk','profile-magic');?></option>
<option value="Asia/Omsk" <?php selected( $value,'Asia/Omsk');?> ><?php _e('Omsk','profile-magic');?></option>
<option value="Asia/Oral" <?php selected( $value,'Asia/Oral');?> ><?php _e('Oral','profile-magic');?></option>
<option value="Asia/Phnom_Penh" <?php selected( $value,'Asia/Phnom Penh');?> ><?php _e('Phnom Penh','profile-magic');?></option>
<option value="Asia/Pontianak" <?php selected( $value,'Asia/Pontianak');?> ><?php _e('Pontianak','profile-magic');?></option>
<option value="Asia/Pyongyang" <?php selected( $value,'Asia/Pyongyang');?> ><?php _e('Pyongyang','profile-magic');?></option>
<option value="Asia/Qatar" <?php selected( $value,'Asia/Qatar');?> ><?php _e('Qatar','profile-magic');?></option>
<option value="Asia/Qyzylorda" <?php selected( $value,'Asia/Qyzylorda');?> ><?php _e('Qyzylorda','profile-magic');?></option>
<option value="Asia/Rangoon" <?php selected( $value,'Asia/Rangoon');?> ><?php _e('Rangoon','profile-magic');?></option>
<option value="Asia/Riyadh" <?php selected( $value,'Asia/Riyadh');?> ><?php _e('Riyadh','profile-magic');?></option>
<option value="Asia/Sakhalin" <?php selected( $value,'Asia/Sakhalin');?> ><?php _e('Sakhalin','profile-magic');?></option>
<option value="Asia/Samarkand" <?php selected( $value,'Asia/Samarkand');?> ><?php _e('Samarkand','profile-magic');?></option>
<option value="Asia/Seoul" <?php selected( $value,'Asia/Seoul');?> ><?php _e('Seoul','profile-magic');?></option>
<option value="Asia/Shanghai" <?php selected( $value,'Asia/Shanghai');?> ><?php _e('Shanghai','profile-magic');?></option>
<option value="Asia/Singapore" <?php selected( $value,'Asia/Singapore');?> ><?php _e('Singapore','profile-magic');?></option>
<option value="Asia/Taipei" <?php selected( $value,'Asia/Taipei');?> ><?php _e('Taipei','profile-magic');?></option>
<option value="Asia/Tashkent" <?php selected( $value,'Asia/Tashkent');?> ><?php _e('Tashkent','profile-magic');?></option>
<option value="Asia/Tbilisi" <?php selected( $value,'TAsia/bilisi');?> ><?php _e('Tbilisi','profile-magic');?></option>
<option value="Asia/Tehran" <?php selected( $value,'Asia/Tehran');?> ><?php _e('Tehran','profile-magic');?></option>
<option value="Asia/Thimphu" <?php selected( $value,'Asia/Thimphu');?> ><?php _e('Thimphu','profile-magic');?></option>
<option value="Asia/Tokyo" <?php selected( $value,'Asia/Tokyo');?> ><?php _e('Tokyo','profile-magic');?></option>
<option value="Asia/Ulaanbaatar" <?php selected( $value,'Asia/Ulaanbaatar');?> ><?php _e('Ulaanbaatar','profile-magic');?></option>
<option value="Asia/Urumqi" <?php selected( $value,'Asia/Urumqi');?> ><?php _e('Urumqi','profile-magic');?></option>
<option value="Asia/Ust-Nera" <?php selected( $value,'Asia/Ust-Nera');?> ><?php _e('Ust-Nera','profile-magic');?></option>
<option value="Asia/Vientiane" <?php selected( $value,'Asia/Vientiane');?> ><?php _e('Vientiane','profile-magic');?></option>
<option value="Asia/Vladivostok" <?php selected( $value,'Asia/Vladivostok');?> ><?php _e('Vladivostok','profile-magic');?></option>
<option value="Asia/Yakutsk" <?php selected( $value,'Asia/Yakutsk');?> ><?php _e('Yakutsk','profile-magic');?></option>
<option value="Asia/Yekaterinburg" <?php selected( $value,'Asia/Yekaterinburg');?> ><?php _e('Yekaterinburg','profile-magic');?></option>
<option value="Asia/Yerevan" <?php selected( $value,'Asia/Yerevan');?> ><?php _e('Yerevan','profile-magic');?></option>
</optgroup>
<optgroup label="Atlantic" >
<option value="Atlantic/Azores" <?php selected( $value,'Atlantic/Azores');?> ><?php _e('Azores','profile-magic');?></option>
<option value="Atlantic/Bermuda" <?php selected( $value,'Atlantic/Bermuda');?> ><?php _e('Bermuda','profile-magic');?></option>
<option value="Atlantic/Canary" <?php selected( $value,'Atlantic/Canary');?> ><?php _e('Canary','profile-magic');?></option>
<option value="Atlantic/Cape_Verde" <?php selected( $value,'Atlantic/Cape Verde');?> ><?php _e('Cape Verde','profile-magic');?></option>
<option value="Atlantic/Faroe" <?php selected( $value,'Atlantic/Faroe');?> ><?php _e('Faroe','profile-magic');?></option>
<option value="Atlantic/Madeira" <?php selected( $value,'Atlantic/Madeira');?> ><?php _e('Madeira','profile-magic');?></option>
<option value="Atlantic/Reykjavik" <?php selected( $value,'Atlantic/Reykjavik');?> ><?php _e('Reykjavik','profile-magic');?></option>
<option value="Atlantic/South_Georgia" <?php selected( $value,'Atlantic/South Georgia');?> ><?php _e('South Georgia','profile-magic');?></option>
<option value="Atlantic/Stanley" <?php selected( $value,'Atlantic/Stanley');?> ><?php _e('Stanley','profile-magic');?></option>
<option value="Atlantic/St_Helena" <?php selected( $value,'Atlantic/St Helena');?> ><?php _e('St Helena','profile-magic');?></option>
</optgroup>
<optgroup label="Australia">
<option value="Australia/Adelaide" <?php selected( $value,'Australia/Adelaide');?> ><?php _e('Adelaide','profile-magic');?></option>
<option value="Australia/Brisbane" <?php selected( $value,'Australia/Brisbane');?> ><?php _e('Brisbane','profile-magic');?></option>
<option value="Australia/Broken_Hill" <?php selected( $value,'Australia/Broken Hill');?> ><?php _e('Broken Hill','profile-magic');?></option>
<option value="Australia/Currie" <?php selected( $value,'Australia/Currie');?> ><?php _e('Currie','profile-magic');?></option>
<option value="Australia/Darwin" <?php selected( $value,'Australia/Darwin');?> ><?php _e('Darwin','profile-magic');?></option>
<option value="Australia/Eucla" <?php selected( $value,'Australia/Eucla');?> ><?php _e('Eucla','profile-magic');?></option>
<option value="Australia/Hobart" <?php selected( $value,'Australia/Hobart');?> ><?php _e('Hobart','profile-magic');?></option>
<option value="Australia/Lindeman" <?php selected( $value,'Australia/Lindeman');?> ><?php _e('Lindeman','profile-magic');?></option>
<option value="Australia/Lord_Howe" <?php selected( $value,'Australia/Windhoek');?> ><?php _e('Lord Howe','profile-magic');?></option>
<option value="Australia/Melbourne" <?php selected( $value,'Australia/Melbourne');?> ><?php _e('Melbourne','profile-magic');?></option>
<option value="Australia/Perth" <?php selected( $value,'Australia/Perth');?> ><?php _e('Perth','profile-magic');?></option>
<option value="Australia/Sydney" <?php selected( $value,'Australia/Sydney');?> ><?php _e('Sydney','profile-magic');?></option>
</optgroup>
<optgroup label="Europe" >
<option value="Europe/Amsterdam" <?php selected( $value,'Europe/Amsterdam');?> ><?php _e('Amsterdam','profile-magic');?></option>
<option value="Europe/Andorra" <?php selected( $value,'Europe/Andorra');?> ><?php _e('Andorra','profile-magic');?></option>
<option value="Europe/Athens" <?php selected( $value,'Europe/Athens');?> ><?php _e('Athens','profile-magic');?></option>
<option value="Europe/Belgrade" <?php selected( $value,'Europe/Belgrade');?> ><?php _e('Belgrade','profile-magic');?></option>
<option value="Europe/Berlin" <?php selected( $value,'Europe/Berlin');?> ><?php _e('Berlin','profile-magic');?></option>
<option value="Europe/Bratislava" <?php selected( $value,'Europe/Bratislava');?> ><?php _e('Bratislava','profile-magic');?></option>
<option value="Europe/Brussels" <?php selected( $value,'Europe/Brussels');?> ><?php _e('Brussels','profile-magic');?></option>
<option value="Europe/Bucharest" <?php selected( $value,'Europe/Bucharest');?> ><?php _e('Bucharest','profile-magic');?></option>
<option value="Europe/Budapest" <?php selected( $value,'Europe/Budapest');?> ><?php _e('Budapest','profile-magic');?></option>
<option value="Europe/Busingen" <?php selected( $value,'Europe/Busingen');?> ><?php _e('Busingen','profile-magic');?></option>
<option value="Europe/Chisinau" <?php selected( $value,'Europe/Chisinau');?> ><?php _e('Chisinau','profile-magic');?></option>
<option value="Europe/Copenhagen" <?php selected( $value,'Europe/Copenhagen');?> ><?php _e('Copenhagen','profile-magic');?></option>
<option value="Europe/Dublin" <?php selected( $value,'Europe/Dublin');?> ><?php _e('Dublin','profile-magic');?></option>
<option value="Europe/Gibraltar" <?php selected( $value,'Europe/Gibraltar');?> ><?php _e('Gibraltar','profile-magic');?></option>
<option value="Europe/Guernsey" <?php selected( $value,'Europe/Guernsey');?> ><?php _e('Guernsey','profile-magic');?></option>
<option value="Europe/Helsinki" <?php selected( $value,'Europe/Helsinki');?> ><?php _e('Helsinki','profile-magic');?></option>
<option value="Europe/Isle_of_Man" <?php selected( $value,'Europe/Isle of Man');?> ><?php _e('Isle of Man','profile-magic');?></option>
<option value="Europe/Istanbul" <?php selected( $value,'Europe/Istanbul');?> ><?php _e('Istanbul','profile-magic');?></option>
<option value="Europe/Jersey" <?php selected( $value,'Europe/Jersey');?> ><?php _e('Jersey','profile-magic');?></option>
<option value="Europe/Kaliningrad" <?php selected( $value,'Europe/Kaliningrad');?> ><?php _e('Kaliningrad','profile-magic');?></option>
<option value="Europe/Kiev" <?php selected( $value,'Europe/Kiev');?> ><?php _e('Kiev','profile-magic');?></option>
<option value="Europe/Lisbon" <?php selected( $value,'Europe/Lisbon');?> ><?php _e('Lisbon','profile-magic');?></option>
<option value="Europe/Ljubljana" <?php selected( $value,'Europe/Ljubljana');?> ><?php _e('Ljubljana','profile-magic');?></option>
<option value="Europe/London" <?php selected( $value,'Europe/London');?> ><?php _e('London','profile-magic');?></option>
<option value="Europe/Luxembourg" <?php selected( $value,'Europe/Luxembourg');?> ><?php _e('Luxembourg','profile-magic');?></option>
<option value="Europe/Madrid" <?php selected( $value,'Europe/Madrid');?> ><?php _e('Madrid','profile-magic');?></option>
<option value="Europe/Malta" <?php selected( $value,'Europe/Malta');?> ><?php _e('Malta','profile-magic');?></option>
<option value="Europe/Mariehamn" <?php selected( $value,'Europe/Mariehamn');?> ><?php _e('Mariehamn','profile-magic');?></option>
<option value="Europe/Minsk" <?php selected( $value,'Europe/Minsk');?> ><?php _e('Minsk','profile-magic');?></option>
<option value="Europe/Monaco" <?php selected( $value,'Europe/Monaco');?> ><?php _e('Monaco','profile-magic');?></option>
<option value="Europe/Moscow" <?php selected( $value,'Europe/Moscow');?> ><?php _e('Moscow','profile-magic');?></option>
<option value="Europe/Oslo" <?php selected( $value,'Europe/Oslo');?> ><?php _e('Oslo','profile-magic');?></option>
<option value="Europe/Paris" <?php selected( $value,'Europe/Paris');?> ><?php _e('Paris','profile-magic');?></option>
<option value="Europe/Podgorica" <?php selected( $value,'Europe/Podgorica');?> ><?php _e('Podgorica','profile-magic');?></option>
<option value="Europe/Prague" <?php selected( $value,'Europe/Prague');?> ><?php _e('Prague','profile-magic');?></option>
<option value="Europe/Riga" <?php selected( $value,'Europe/Riga');?> ><?php _e('Riga','profile-magic');?></option>
<option value="Europe/Rome" <?php selected( $value,'Europe/Rome');?> ><?php _e('Rome','profile-magic');?></option>
<option value="Europe/Samara" <?php selected( $value,'Europe/Samara');?> ><?php _e('Samara','profile-magic');?></option>
<option value="Europe/San_Marino" <?php selected( $value,'Europe/San Marino');?> ><?php _e('San Marino','profile-magic');?></option>
<option value="Europe/Sarajevo" <?php selected( $value,'Europe/Sarajevo');?> ><?php _e('Sarajevo','profile-magic');?></option>
<option value="Europe/Simferopol" <?php selected( $value,'Europe/Simferopol');?> ><?php _e('Simferopol','profile-magic');?></option>
<option value="Europe/Skopje" <?php selected( $value,'Europe/Skopje');?> ><?php _e('Skopje','profile-magic');?></option>
<option value="Europe/Sofia" <?php selected( $value,'Europe/Sofia');?> ><?php _e('Sofia','profile-magic');?></option>
<option value="Europe/Stockholm" <?php selected( $value,'Europe/Stockholm');?> ><?php _e('Stockholm','profile-magic');?></option>
<option value="Europe/Tallinn" <?php selected( $value,'Europe/Tallinn');?> ><?php _e('Tallinn','profile-magic');?></option>
<option value="Europe/Tirane" <?php selected( $value,'Europe/Tirane');?> ><?php _e('Tirane','profile-magic');?></option>
<option value="Europe/Uzhgorod" <?php selected( $value,'Europe/Uzhgorod');?> ><?php _e('Uzhgorod','profile-magic');?></option>
<option value="Europe/Vaduz" <?php selected( $value,'Europe/Vaduz');?> ><?php _e('Vaduz','profile-magic');?></option>
<option value="Europe/Vatican" <?php selected( $value,'Europe/Vatican');?> ><?php _e('Vatican','profile-magic');?></option>
<option value="Europe/Vienna" <?php selected( $value,'Europe/Vienna');?> ><?php _e('Vienna','profile-magic');?></option>
<option value="Europe/Vilnius" <?php selected( $value,'Europe/Vilnius');?> ><?php _e('Vilnius','profile-magic');?></option>
<option value="Europe/Volgograd" <?php selected( $value,'Europe/Volgograd');?> ><?php _e('Volgograd','profile-magic');?></option>
<option value="Europe/Warsaw" <?php selected( $value,'Europe/Warsaw');?> ><?php _e('Warsaw','profile-magic');?></option>
<option value="Europe/Zagreb" <?php selected( $value,'Europe/Zagreb');?> ><?php _e('Zagreb','profile-magic');?></option>
<option value="Europe/Zaporozhye" <?php selected( $value,'Europe/Zaporozhye');?> ><?php _e('Zaporozhye','profile-magic');?></option>
<option value="Europe/Zurich" <?php selected( $value,'Europe/Zurich');?> ><?php _e('Zurich','profile-magic');?></option>
</optgroup>
<optgroup label="Indian" >
<option value="Indian/Antananarivo" <?php selected( $value,'Indian/Antananarivo');?> ><?php _e('Antananarivo','profile-magic');?></option>
<option value="Indian/Chagos" <?php selected( $value,'Indian/Chagos');?> ><?php _e('Chagos','profile-magic');?></option>
<option value="Indian/Christmas" <?php selected( $value,'Indian/Christmas');?> ><?php _e('Christmas','profile-magic');?></option>
<option value="Indian/Cocos" <?php selected( $value,'Indian/Cocos');?> ><?php _e('Cocos','profile-magic');?></option>
<option value="Indian/Comoro" <?php selected( $value,'Indian/Comoro');?> ><?php _e('Comoro','profile-magic');?></option>
<option value="Indian/Kerguelen" <?php selected( $value,'Indian/Kerguelen');?> ><?php _e('Kerguelen','profile-magic');?></option>
<option value="Indian/Mahe" <?php selected( $value,'Indian/Mahe');?> ><?php _e('Mahe','profile-magic');?></option>
<option value="Indian/Maldives" <?php selected( $value,'Indian/Maldives');?> ><?php _e('Maldives','profile-magic');?></option>
<option value="Indian/Mauritius" <?php selected( $value,'Indian/Mauritius');?> ><?php _e('Mauritius','profile-magic');?></option>
<option value="Indian/Mayotte" <?php selected( $value,'Indian/Mayotte');?> ><?php _e('Mayotte','profile-magic');?></option>
<option value="Indian/Reunion" <?php selected( $value,'Indian/Reunion');?> ><?php _e('Reunion','profile-magic');?></option>
</optgroup>
<optgroup label="Pacific" >
<option value="Pacific/Apia" <?php selected( $value,'Pacific/Apia');?> ><?php _e('Apia','profile-magic');?></option>
<option value="Pacific/Auckland" <?php selected( $value,'Pacific/Auckland');?> ><?php _e('Auckland','profile-magic');?></option>
<option value="Pacific/Chatham" <?php selected( $value,'Pacific/Chatham');?> ><?php _e('Chatham','profile-magic');?></option>
<option value="Pacific/Chuuk" <?php selected( $value,'Pacific/Chuuk');?> ><?php _e('Chuuk','profile-magic');?></option>
<option value="Pacific/Easter" <?php selected( $value,'Pacific/Easter');?> ><?php _e('Easter','profile-magic');?></option>
<option value="Pacific/Efate" <?php selected( $value,'Pacific/Efate');?> ><?php _e('Efate','profile-magic');?></option>
<option value="Pacific/Enderbury" <?php selected( $value,'Pacific/Enderbury');?> ><?php _e('Enderbury','profile-magic');?></option>
<option value="Pacific/Fakaofo" <?php selected( $value,'Pacific/Fakaofo');?> ><?php _e('Fakaofo','profile-magic');?></option>
<option value="Pacific/Fiji" <?php selected( $value,'Pacific/Fiji');?> ><?php _e('Fiji','profile-magic');?></option>
<option value="Pacific/Funafuti" <?php selected( $value,'Pacific/Funafuti');?> ><?php _e('Funafuti','profile-magic');?></option>
<option value="Pacific/Galapagos" <?php selected( $value,'Pacific/Galapagos');?> ><?php _e('Galapagos','profile-magic');?></option>
<option value="Pacific/Gambier" <?php selected( $value,'Pacific/Gambier');?> ><?php _e('Gambier','profile-magic');?></option>
<option value="Pacific/Guadalcanal" <?php selected( $value,'Pacific/Guadalcanal');?> ><?php _e('Guadalcanal','profile-magic');?></option>
<option value="Pacific/Guam" <?php selected( $value,'Pacific/Guam');?> ><?php _e('Guam','profile-magic');?></option>
<option value="Pacific/Honolulu" <?php selected( $value,'Pacific/Honolulu');?> ><?php _e('Honolulu','profile-magic');?></option>
<option value="Pacific/Johnston" <?php selected( $value,'Pacific/Johnston');?> ><?php _e('Johnston','profile-magic');?></option>
<option value="Pacific/Kiritimati" <?php selected( $value,'Pacific/Kiritimati');?> ><?php _e('Kiritimati','profile-magic');?></option>
<option value="Pacific/Kosrae" <?php selected( $value,'Pacific/Kosrae');?> ><?php _e('Kosrae','profile-magic');?></option>
<option value="Pacific/Kwajalein" <?php selected( $value,'Pacific/Kwajalein');?> ><?php _e('Kwajalein','profile-magic');?></option>
<option value="Pacific/Majuro" <?php selected( $value,'Pacific/Majuro');?> ><?php _e('Majuro','profile-magic');?></option>
<option value="Pacific/Marquesas" <?php selected( $value,'Pacific/Marquesas');?> ><?php _e('Marquesas','profile-magic');?></option>
<option value="Pacific/Midway" <?php selected( $value,'Pacific/Midway');?> ><?php _e('Midway','profile-magic');?></option>
<option value="Pacific/Nauru" <?php selected( $value,'Pacific/Nauru');?> ><?php _e('Nauru','profile-magic');?></option>
<option value="Pacific/Niue" <?php selected( $value,'Pacific/Niue');?> ><?php _e('Niue','profile-magic');?></option>
<option value="Pacific/Norfolk" <?php selected( $value,'Pacific/Norfolk');?> ><?php _e('Norfolk','profile-magic');?></option>
<option value="Pacific/Noumea" <?php selected( $value,'Pacific/Noumea');?> ><?php _e('Noumea','profile-magic');?></option>
<option value="Pacific/Pago_Pago" <?php selected( $value,'Pacific/Pago Pago');?> ><?php _e('Pago Pago','profile-magic');?></option>
<option value="Pacific/Palau" <?php selected( $value,'Pacific/Palau');?> ><?php _e('Palau','profile-magic');?></option>
<option value="Pacific/Pitcairn" <?php selected( $value,'Pacific/Pitcairn');?> ><?php _e('Pitcairn','profile-magic');?></option>
<option value="Pacific/Pohnpei" <?php selected( $value,'Pacific/Pohnpei');?> ><?php _e('Pohnpei','profile-magic');?></option>
<option value="Pacific/Port_Moresby" <?php selected( $value,'Pacific/Port Moresby');?> ><?php _e('Port Moresby','profile-magic');?></option>
<option value="Pacific/Rarotonga" <?php selected( $value,'Pacific/Rarotonga');?> ><?php _e('Rarotonga','profile-magic');?></option>
<option value="Pacific/Saipan" <?php selected( $value,'Pacific/Saipan');?> ><?php _e('Saipan','profile-magic');?></option>
<option value="Pacific/Tahiti" <?php selected( $value,'Pacific/Tahiti');?> ><?php _e('Tahiti','profile-magic');?></option>
<option value="Pacific/Tarawa" <?php selected( $value,'Pacific/Tarawa');?> ><?php _e('Tarawa','profile-magic');?></option>
<option value="Pacific/Tongatapu" <?php selected( $value,'Pacific/Tongatapu');?> ><?php _e('Tongatapu','profile-magic');?></option>
<option value="Pacific/Wake" <?php selected( $value,'Pacific/Wake');?> ><?php _e('Wake','profile-magic');?></option>
<option value="Pacific/Wallis" <?php selected( $value,'Pacific/Wallis');?> ><?php _e('Wallis','profile-magic');?></option>
</optgroup>
<optgroup label="UTC" >
<option value="UTC" <?php selected( $value,'UTC');?> ><?php _e('UTC','profile-magic');?></option>
</optgroup>
<optgroup label="Manual Offsets">
<option value="UTC-12" <?php selected( $value,'UTC-12');?> ><?php _e('UTC-12','profile-magic');?></option>
<option value="UTC-11.5" <?php selected( $value,'UTC-11:30');?> ><?php _e('UTC-11:30','profile-magic');?></option>
<option value="UTC-11" <?php selected( $value,'UTC-11');?> ><?php _e('UTC-11','profile-magic');?></option>
<option value="UTC-10.5" <?php selected( $value,'UTC-10:30');?> ><?php _e('UTC-10:30','profile-magic');?></option>
<option value="UTC-10" <?php selected( $value,'UTC-10');?> ><?php _e('UTC-10','profile-magic');?></option>
<option value="UTC-9.5" <?php selected( $value,'UTC-9:30');?> ><?php _e('UTC-9:30','profile-magic');?></option>
<option value="UTC-9" <?php selected( $value,'UTC-9');?> ><?php _e('UTC-9','profile-magic');?></option>
<option value="UTC-8.5" <?php selected( $value,'UTC-8:30');?> ><?php _e('UTC-8:30','profile-magic');?></option>
<option value="UTC-8" <?php selected( $value,'UTC-8');?> ><?php _e('UTC-8','profile-magic');?></option>
<option value="UTC-7.5" <?php selected( $value,'UTC-7:30');?> ><?php _e('UTC-7:30','profile-magic');?></option>
<option value="UTC-7" <?php selected( $value,'UTC-7');?> ><?php _e('UTC-7','profile-magic');?></option>
<option value="UTC-6.5" <?php selected( $value,'UTC-6:30');?> ><?php _e('UTC-6:30','profile-magic');?></option>
<option value="UTC-6" <?php selected( $value,'UTC-6');?> ><?php _e('UTC-6','profile-magic');?></option>
<option value="UTC-5.5" <?php selected( $value,'UTC-5:30');?> ><?php _e('UTC-5:30','profile-magic');?></option>
<option value="UTC-5" <?php selected( $value,'UTC-5');?> ><?php _e('UTC-5','profile-magic');?></option>
<option value="UTC-4.5" <?php selected( $value,'UTC-4:30');?> ><?php _e('UTC-4:30','profile-magic');?></option>
<option value="UTC-4" <?php selected( $value,'UTC-4');?> ><?php _e('UTC-4','profile-magic');?></option>
<option value="UTC-3.5" <?php selected( $value,'UTC-3:30');?> ><?php _e('UTC-3:30','profile-magic');?></option>
<option value="UTC-3" <?php selected( $value,'UTC-3');?> ><?php _e('UTC-3','profile-magic');?></option>
<option value="UTC-2.5" <?php selected( $value,'UTC-2:30');?> ><?php _e('UTC-2:30','profile-magic');?></option>
<option value="UTC-2" <?php selected( $value,'UTC-2');?> ><?php _e('UTC-2','profile-magic');?></option>
<option value="UTC-1.5" <?php selected( $value,'UTC-1:30');?> ><?php _e('UTC-1:30','profile-magic');?></option>
<option value="UTC-1" <?php selected( $value,'UTC-1');?> ><?php _e('UTC-1','profile-magic');?></option>
<option value="UTC-0.5" <?php selected( $value,'UTC-0:30');?> ><?php _e('UTC-0:30','profile-magic');?></option>
<option value="UTC+0" <?php selected( $value,'UTC+0');?> ><?php _e('UTC+0','profile-magic');?></option>
<option value="UTC+0.5" <?php selected( $value,'UTC+0:30');?> ><?php _e('UTC+0:30','profile-magic');?></option>
<option value="UTC+1" <?php selected( $value,'UTC+1');?> ><?php _e('UTC+1','profile-magic');?></option>
<option value="UTC+1.5" <?php selected( $value,'UTC+1:30');?> ><?php _e('UTC+1:30','profile-magic');?></option>
<option value="UTC+2" <?php selected( $value,'UTC+2');?> ><?php _e('UTC+2','profile-magic');?></option>
<option value="UTC+2.5" <?php selected( $value,'UTC+2:30');?> ><?php _e('UTC+2:30','profile-magic');?></option>
<option value="UTC+3" <?php selected( $value,'UTC+3');?> ><?php _e('UTC+3','profile-magic');?></option>
<option value="UTC+3.5" <?php selected( $value,'UTC+3:30');?> ><?php _e('UTC+3:30','profile-magic');?></option>
<option value="UTC+4" <?php selected( $value,'UTC+4');?> ><?php _e('UTC+4','profile-magic');?></option>
<option value="UTC+4.5" <?php selected( $value,'UTC+4:30');?> ><?php _e('UTC+4:30','profile-magic');?></option>
<option value="UTC+5" <?php selected( $value,'UTC+5');?> ><?php _e('UTC+5','profile-magic');?></option>
<option value="UTC+5.5" <?php selected( $value,'UTC+5:30');?> ><?php _e('UTC+5:30','profile-magic');?></option>
<option value="UTC+5.75" <?php selected( $value,'UTC+5:45');?> ><?php _e('UTC+5:45','profile-magic');?></option>
<option value="UTC+6" <?php selected( $value,'UTC+6');?> ><?php _e('UTC+6','profile-magic');?></option>
<option value="UTC+6.5" <?php selected( $value,'UTC+6:30');?> ><?php _e('UTC+6:30','profile-magic');?></option>
<option value="UTC+7" <?php selected( $value,'UTC+7');?> ><?php _e('UTC+7','profile-magic');?></option>
<option value="UTC+7.5" <?php selected( $value,'UTC+7:30');?> ><?php _e('UTC+7:30','profile-magic');?></option>
<option value="UTC+8" <?php selected( $value,'UTC+8');?> ><?php _e('UTC+8','profile-magic');?></option>
<option value="UTC+8.5" <?php selected( $value,'UTC+8:30');?> ><?php _e('UTC+8:30','profile-magic');?></option>
<option value="UTC+8.75" <?php selected( $value,'UTC+8:45');?> ><?php _e('UTC+8:45','profile-magic');?></option>
<option value="UTC+9" <?php selected( $value,'UTC+9');?> ><?php _e('UTC+9','profile-magic');?></option>
<option value="UTC+9.5" <?php selected( $value,'UTC+9:30');?> ><?php _e('UTC+9:30','profile-magic');?></option>
<option value="UTC+10" <?php selected( $value,'UTC+10');?> ><?php _e('UTC+10','profile-magic');?></option>
<option value="UTC+10.5" <?php selected( $value,'UTC+10:30');?> ><?php _e('UTC+10:30','profile-magic');?></option>
<option value="UTC+11" <?php selected( $value,'UTC+11');?> ><?php _e('UTC+11','profile-magic');?></option>
<option value="UTC+11.5" <?php selected( $value,'UTC+11:30');?> ><?php _e('UTC+11:30','profile-magic');?></option>
<option value="UTC+12" <?php selected( $value,'UTC+12');?> ><?php _e('UTC+12','profile-magic');?></option>
<option value="UTC+12.75" <?php selected( $value,'UTC+12:45');?> ><?php _e('UTC+12:45','profile-magic');?></option>
<option value="UTC+13" <?php selected( $value,'UTC+13');?> ><?php _e('UTC+13','profile-magic');?></option>
<option value="UTC+13.75" <?php selected( $value,'UTC+13:45');?> ><?php _e('UTC+13:45','profile-magic');?></option>
<option value="UTC+14" <?php selected( $value,'UTC+14');?> ><?php _e('>UTC+14','profile-magic');?></option>
</optgroup>